const MapletonImages = {
    image1: require("../../images/ForSale/WhiteHome/56.jpg").default,
    image2: require("../../images/ForSale/WhiteHome/57.jpg").default,
    image3: require("../../images/ForSale/WhiteHome/58.jpg").default,
    image4: require("../../images/ForSale/WhiteHome/59.jpg").default,
    image5: require("../../images/ForSale/WhiteHome/60.jpg").default,
    image6: require("../../images/ForSale/WhiteHome/61.jpg").default,
    image7: require("../../images/ForSale/WhiteHome/62.jpg").default,
    image8: require("../../images/ForSale/WhiteHome/63.jpg").default,
    image9: require("../../images/ForSale/WhiteHome/64.jpg").default,
    image10: require("../../images/ForSale/WhiteHome/65.jpg").default,
    image11: require("../../images/ForSale/WhiteHome/66.jpg").default,
    image12: require("../../images/ForSale/WhiteHome/67.jpg").default,
    image13: require("../../images/ForSale/WhiteHome/68.jpg").default,
    image14: require("../../images/ForSale/WhiteHome/69.jpg").default,
    image15: require("../../images/ForSale/WhiteHome/70.jpg").default,
    image16: require("../../images/ForSale/WhiteHome/71.jpg").default,
    image17: require("../../images/ForSale/WhiteHome/72.jpg").default,
    image18: require("../../images/ForSale/WhiteHome/73.jpg").default,
    image19: require("../../images/ForSale/WhiteHome/74.jpg").default,
    image20: require("../../images/ForSale/WhiteHome/75.jpg").default,
    image21: require("../../images/ForSale/WhiteHome/76.jpg").default,
    image22: require("../../images/ForSale/WhiteHome/77.jpg").default,
    image23: require("../../images/ForSale/WhiteHome/78.jpg").default,
    image24: require("../../images/ForSale/WhiteHome/79.jpg").default,
    image25: require("../../images/ForSale/WhiteHome/80.jpg").default,
    image26: require("../../images/ForSale/WhiteHome/81.jpg").default,
    image27: require("../../images/ForSale/WhiteHome/82.jpg").default,
    image28: require("../../images/ForSale/WhiteHome/83.jpg").default,
    image29: require("../../images/ForSale/WhiteHome/84.jpg").default,
}

export default MapletonImages;