const MapletonImages = [
    require("../../images/ForSale/WhiteHome/56.jpg").default,
    require("../../images/ForSale/WhiteHome/57.jpg").default,
    require("../../images/ForSale/WhiteHome/58.jpg").default,
    require("../../images/ForSale/WhiteHome/59.jpg").default,
    require("../../images/ForSale/WhiteHome/60.jpg").default,
    require("../../images/ForSale/WhiteHome/61.jpg").default,
    require("../../images/ForSale/WhiteHome/62.jpg").default,
    require("../../images/ForSale/WhiteHome/63.jpg").default,
    require("../../images/ForSale/WhiteHome/64.jpg").default,
    require("../../images/ForSale/WhiteHome/65.jpg").default,
    require("../../images/ForSale/WhiteHome/66.jpg").default,
    require("../../images/ForSale/WhiteHome/67.jpg").default,
    require("../../images/ForSale/WhiteHome/68.jpg").default,
    require("../../images/ForSale/WhiteHome/69.jpg").default,
    require("../../images/ForSale/WhiteHome/70.jpg").default,
    require("../../images/ForSale/WhiteHome/71.jpg").default,
    require("../../images/ForSale/WhiteHome/72.jpg").default,
    require("../../images/ForSale/WhiteHome/73.jpg").default,
    require("../../images/ForSale/WhiteHome/74.jpg").default,
    require("../../images/ForSale/WhiteHome/75.jpg").default,
    require("../../images/ForSale/WhiteHome/76.jpg").default,
    require("../../images/ForSale/WhiteHome/77.jpg").default,
    require("../../images/ForSale/WhiteHome/78.jpg").default,
    require("../../images/ForSale/WhiteHome/79.jpg").default,
    require("../../images/ForSale/WhiteHome/80.jpg").default,
    require("../../images/ForSale/WhiteHome/81.jpg").default,
    require("../../images/ForSale/WhiteHome/82.jpg").default,
    require("../../images/ForSale/WhiteHome/83.jpg").default,
    require("../../images/ForSale/WhiteHome/84.jpg").default,
]

export default MapletonImages;