const MapletonImages = [
    require("../../images/WhiteHome/0.webp").default,
    require("../../images/WhiteHome/1.webp").default,
    require("../../images/WhiteHome/2.webp").default,
    require("../../images/WhiteHome/3.webp").default,
    require("../../images/WhiteHome/4.webp").default,
    require("../../images/WhiteHome/5.webp").default,
    require("../../images/WhiteHome/6.webp").default,
    require("../../images/WhiteHome/7.webp").default,
    require("../../images/WhiteHome/8.webp").default,
    require("../../images/WhiteHome/9.webp").default,
    require("../../images/WhiteHome/10.webp").default,
    require("../../images/WhiteHome/11.webp").default,
    require("../../images/WhiteHome/12.webp").default,
    require("../../images/WhiteHome/13.webp").default,
    require("../../images/WhiteHome/14.webp").default,
    require("../../images/WhiteHome/15.webp").default,
    require("../../images/WhiteHome/16.webp").default,
    require("../../images/WhiteHome/17.webp").default,
    require("../../images/WhiteHome/18.webp").default,
    require("../../images/WhiteHome/19.webp").default,
    require("../../images/WhiteHome/20.webp").default,
    require("../../images/WhiteHome/21.webp").default,
    require("../../images/WhiteHome/22.webp").default,
    require("../../images/WhiteHome/23.webp").default,
    require("../../images/WhiteHome/24.webp").default,
    require("../../images/WhiteHome/25.webp").default,
    require("../../images/WhiteHome/26.webp").default,
    require("../../images/WhiteHome/27.webp").default,
    require("../../images/WhiteHome/28.webp").default,
    require("../../images/WhiteHome/29.webp").default,
    require("../../images/WhiteHome/30.webp").default,
    require("../../images/WhiteHome/31.webp").default,
]

export default MapletonImages;